'use client';
import type { Metadata } from "next";
import Layout from "./components/Layout";
import { useState } from "react";
import Login from "./components/Login";
// export const metadata: Metadata = {
//   title: "Dietsync",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [logado, setLogado] = useState(true);
  return (
    <html lang="en">
      <body>
        {logado ? (
          // Se estiver logado, exibe o Layout
          <Layout>{children}</Layout>
        ) : (
          // Se não estiver logado, exibe a tela de Login
          <Login />
        )}
      </body>
    </html>
  );
}