'use client';
import type { Metadata } from "next";
import Layout from "./components/Layout";
import { useState } from "react";
import Login from "./components/Login";
import { AuthProvider } from "./contexts/AuthContext";
// export const metadata: Metadata = {
//   title: "Dietsync",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}