'use client';
import { AuthProvider } from "./contexts/AuthContext";
// export const metadata: Metadata = {
//   title: "Dietsync",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}